# Site settings
title: Chris Nagel
subtitle: Ik ben maar gewoon een hulpie
email:
description:

baseurl: "//studioalloy.nl/chrisnagel/" # the subpath of your site, e.g. /blog/
url: "//studioalloy.nl/chrisnagel/" # the base hostname & protocol for your site

default_image: img/chris-nagel.jpg

vimeo: 154053478

twitter_username:
github_username:

# Collections
collections:
  team:
    output: false

# Build settings
markdown: kramdown
