# Site settings
title: Chris Nagel
subtitle: Ik ben maar gewoon een hulpie
email:
description: Dit is een film voor en over mijn opa, het is een portret van Chris Nagel.

baseurl: "//chrisnagel.nl/" # the subpath of your site, e.g. /blog/
url: "//chrisnagel.nl/" # the base hostname & protocol for your site

default_image: chris-nagel.jpg

vimeo: 154714104

twitter_username: adays
github_username: adays

# Collections
collections:
  team:
    output: false

# Build settings
markdown: kramdown
